name: Deploy DocC to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install development Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          development: true
          check-latest: true
          cache-snapshot: false
      - name: build docc
        run: |
          swift package --allow-writing-to-directory ./docs generate-documentation \
          --enable-experimental-combined-documentation \
          --target TestingDocC \
          --target AnotherTarget \
          --disable-indexing \
          --output-path ./docs \
          --transform-for-static-hosting \
          --hosting-base-path TestingDocC
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

